#!/usr/bin/env bash
#
# Stand up the end-to-end environment: local Supabase (same images as
# production), the fake Enable Banking API, and an .env.e2e for the app.
#
# Deliberately never reads .env.local. That file points at the PRODUCTION
# database; an E2E suite that boots against it would write test companies,
# journal entries and bank connections into real customer data.
#
# Usage:  bash tests/e2e/setup-env.sh
#
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
FAKES="$ROOT/tests/e2e/fakes"
ENV_FILE="$ROOT/.env.e2e"
FAKE_EB_PORT="${FAKE_EB_PORT:-4010}"

say() { printf '\n\033[1m%s\033[0m\n' "$*"; }

# --------------------------------------------------------------------------
say "1/4  Test keypair for the Enable Banking JWT"
# --------------------------------------------------------------------------
# Generated, never committed: lib/jwt.ts signs RS256 with this key and the fake
# verifies the signature, so a signing regression fails the suite.
if [ ! -f "$FAKES/eb-test-private.pem" ]; then
  openssl genpkey -algorithm RSA -pkeyopt rsa_keygen_bits:2048 \
    -out "$FAKES/eb-test-private.pem" 2>/dev/null
  openssl rsa -in "$FAKES/eb-test-private.pem" -pubout \
    -out "$FAKES/eb-test-public.pem" 2>/dev/null
  echo "generated a fresh 2048-bit keypair"
else
  echo "reusing the existing keypair"
fi
EB_PRIVATE_B64="$(base64 -i "$FAKES/eb-test-private.pem" | tr -d '\n')"

# --------------------------------------------------------------------------
say "2/4  Local Supabase"
# --------------------------------------------------------------------------
if ! docker ps --format '{{.Names}}' | grep -q "^supabase_db_"; then
  echo "starting (this applies every migration in supabase/migrations/, so the"
  echo "schema carries the real triggers, RLS policies and RPCs)"
  (cd "$ROOT" && supabase start)
else
  echo "already running"
fi

# supabase status prints the keys the app needs as shell assignments.
eval "$(cd "$ROOT" && supabase status -o env)"

# The local image does not grant anon/authenticated/service_role the DML that
# a hosted project grants them, so without this every PostgREST call fails
# with "permission denied for table X". See supabase/seed.sql.
DB_CONTAINER="$(docker ps --format '{{.Names}}' | grep '^supabase_db_' | head -1)"
docker exec -i "$DB_CONTAINER" psql -U postgres -v ON_ERROR_STOP=1 -q \
  < "$ROOT/supabase/seed.sql" 2>/dev/null
echo "privileges aligned with a hosted project (RLS untouched)"

# --------------------------------------------------------------------------
say "3/4  .env.e2e"
# --------------------------------------------------------------------------
cat > "$ENV_FILE" <<EOF
# Generated by tests/e2e/setup-env.sh. Do not edit by hand, do not commit.
#
# Points at the LOCAL Supabase stack. Never at production.

NEXT_PUBLIC_SUPABASE_URL=${API_URL}
NEXT_PUBLIC_SUPABASE_ANON_KEY=${ANON_KEY}
SUPABASE_SERVICE_ROLE_KEY=${SERVICE_ROLE_KEY}

NEXT_PUBLIC_APP_URL=http://localhost:3000

# MFA on, matching hosted. The E2E suite enrols TOTP and computes the codes,
# so this stays true rather than being switched off for convenience: the
# enrolment step is part of what onboarding has to get right.
NEXT_PUBLIC_REQUIRE_MFA=true
NEXT_PUBLIC_SELF_HOSTED=false

# Enable Banking, pointed at the fake in tests/e2e/fakes/.
ENABLE_BANKING_API_URL=http://localhost:${FAKE_EB_PORT}
ENABLE_BANKING_APP_ID=e2e-test-app-id
ENABLE_BANKING_PRIVATE_KEY=${EB_PRIVATE_B64}
ENABLE_BANKING_SANDBOX=true
ENABLE_BANKING_PSU_TYPE=business

CRON_SECRET=e2e-cron-secret
EOF
echo "wrote $ENV_FILE"

# --------------------------------------------------------------------------
say "4/4  Fake Enable Banking API"
# --------------------------------------------------------------------------
if curl -sf "http://localhost:${FAKE_EB_PORT}/__fake/health" >/dev/null 2>&1; then
  echo "already running on :${FAKE_EB_PORT}"
else
  FAKE_EB_PORT="$FAKE_EB_PORT" \
  FAKE_EB_PUBLIC_KEY="$(cat "$FAKES/eb-test-public.pem")" \
    node "$FAKES/enable-banking-server.mjs" > "$ROOT/tests/e2e/.fake-eb.log" 2>&1 &
  echo "started on :${FAKE_EB_PORT} (log: tests/e2e/.fake-eb.log)"
fi

say "Ready"
cat <<EOF
Supabase API   ${API_URL}
Supabase Studio $(cd "$ROOT" && supabase status -o env | grep STUDIO_URL | cut -d= -f2- | tr -d '"')
Fake bank API  http://localhost:${FAKE_EB_PORT}

Start the app against it:
  npm run dev -- --port 3000   # with the env from .env.e2e
EOF
